FROM node:22-alpine

WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

CMD ["sh", "-c", "pnpm install --frozen-lockfile --store-dir /pnpm/store && pnpm --filter @grocersync/api prisma:generate && pnpm --dir apps/api exec prisma db push --schema prisma/schema.prisma && exec pnpm --filter @grocersync/api dev"]
